### ISSUE TITLE
Fix the unclosed ClientSession warnings

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla/tctalker#11]
More details in  https://github.com/mozilla/tctalker/pull/9

**Comment by escapewindow** [comment]
`09:50 <aki> mtabara:` [here](https://github.com/mozilla/tctalker/blob/master/src/tctalker/tctalker.py#L128)

```python
loop = asyncio.get_event_loop()
loop.run_until_complete(async_main())
loop.close()
```
```
09:51 <aki> i think the close will fix the error. worth a try
```

**Comment by MihaiTabara** [comment]
Fixed by @escapewindow under https://github.com/mozilla/tctalker/commit/f11b30838044dadc93c73f4d3ae8f19095ff05c3
