### ISSUE TITLE
support `cancel_graph`

### ISSUE THREAD

**Issue by rail** [mozilla/tctalker#2]
It would be great to teach tctalker how to walk the graph and cancel all pending/running tasks in case we need to cancel all of them for some reason.

**Comment by lundjordan** [comment]
:+1:

**Comment by MihaiTabara** [comment]
This sounds like the perfect opportunity for me to resume to my algorithms background from topcoder times back in the days :) want me to take this?

**Comment by rail** [comment]
It would be great! Thank you.

**Comment by MihaiTabara** [comment]
Merged a PR that solves this. Closing the issue.
